variables:
  COMPILER_FLAGS: -O3

stages:
- main

before_script:
  - export CMAKE_FLAGS="-DCMAKE_CXX_FLAGS='$COMPILER_FLAGS'"

build_job:
  stage: main
  tags:
  - docker
  image: citcat/dune-env:latest
  script:
  - cd /opt/dune
  - ./dune-common/bin/dunecontrol update
  - export DUNE_CONTROL_PATH=/opt/dune:$CI_PROJECT_DIR
  - ./dune-common/bin/dunecontrol --module=citcat all
  - ./dune-common/bin/dunecontrol --only=citcat make doc

build_ubuntu:
  stage: build
  tags:
  - docker
  image: ubuntu:latest
  script:
  - cd ..
  - apt-get update && apt-get install -y cmake doxygen gcc g++ gfortran git pkg-config
  - git clone https://gitlab.dune-project.org/staging/dune-uggrid.git
  - git clone https://gitlab.dune-project.org/core/dune-common
  - git clone https://gitlab.dune-project.org/core/dune-geometry
  - git clone https://gitlab.dune-project.org/core/dune-grid
  - ./dune-common/bin/dunecontrol all
  - ./dune-common/bin/dunecontrol --only=citcat make doc