---
image: ccees/utopia:bionic

variables:
  CPUS_MULTICORE: 3
  CPUS_DIND: 3
  DUNE_CONTROL_PATH: /opt/dune:$CI_PROJECT_DIR  # such that DUNE finds Utopia
  RUN_IN_DUNE_ENV: $CI_PROJECT_DIR/build-cmake/run-in-dune-env
  CONFIG_FLAGS:
      -DDUNE_PYTHON_VIRTUALENV_SETUP=True
      -DDUNE_PYTHON_ALLOW_GET_PIP=True
  MAKE_FLAGS_BUILD:
      -j $CPUS_MULTICORE
  MODEL_DIR: $CI_PROJECT_DIR/dune/utopia/models
  DUNE_ENV_IMAGE: ccees/utopia:bionic

stages:
  - setup
  - build
  - test

before_script:
  ## Enter dune directory
  - cd /opt/dune
  ##
  ## For outside dependencies, use the "Utopia CI" deploy key
  ## Instructions:
  ##   https://docs.gitlab.com/ce/ci/ssh_keys/
  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  ##
  ## Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  ## 
  ## Add the known hosts lists to ensure this ssh connection is the right one
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config' # FIXME


# Setup stage -----------------------------------------------------------------
# Updates the docker image to be used for the build and test stages
setup:update-dune:
  stage: setup
  tags:
    - dind
  image: docker:stable
  services:
    - docker:dind
  variables:
    # Use the driver recommended for DIND, see documentation:
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_DRIVER: overlay2
  only:
    - master
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
  script:
    - docker build --build-arg PROCNUM=$CPUS_DIND -f docker/dune-env-update.dockerfile -t $DUNE_ENV_IMAGE .
    - docker push $DUNE_ENV_IMAGE


# Build stage -----------------------------------------------------------------
# Build the tests and the models
# The artifacts of these jobs are needed in the test stage
build:tests:
  stage: build
  artifacts: &shared_artifacts
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build-cmake
    expire_in: 3 hours
  script:
    - CMAKE_FLAGS="$CONFIG_FLAGS"
      ./dune-common/bin/dunecontrol --module=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD build_tests

build:models:
  stage: build
  artifacts:
    <<: *shared_artifacts
  script:
    - CMAKE_FLAGS="$CONFIG_FLAGS"
      ./dune-common/bin/dunecontrol --module=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD all

build:debug:
  stage: build
  allow_failure: true
  script:
    - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CONFIG_FLAGS -DCMAKE_CXX_FLAGS_DEBUG='$CMAKE_CXX_FLAGS_DEBUG -Werror'"
      ./dune-common/bin/dunecontrol --only=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD build_tests
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD all


# Test stage ------------------------------------------------------------------
# Using the artifacts of the build stage, executes tests of core, data i/o,
# frontend, and models.
test:core:
  stage: test
  dependencies:
    - build:tests
  script:
    - ./dune-common/bin/dunecontrol --only=utopia make test_core

test:dataio:
  stage: test
  dependencies:
    - build:tests
  script:
    - ./dune-common/bin/dunecontrol --only=utopia make test_dataio

test:python:
  stage: test
  dependencies:
    - build:models
  script:
    - ./dune-common/bin/dunecontrol --only=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make test_python

test:models:
  stage: test
  dependencies:
    - build:models
  script:
    - ./dune-common/bin/dunecontrol --only=utopia configure
    # test the default model config
    - $RUN_IN_DUNE_ENV utopia dummy
    # test a configuration that allows a sweep
    - $RUN_IN_DUNE_ENV utopia dummy $MODEL_DIR/dummy/test/sweep.yml --sweep --note sweep
    # test the other models
    - $RUN_IN_DUNE_ENV utopia SimpleEG
    # - $RUN_IN_DUNE_ENV utopia SimpleEG $MODEL_DIR/SimpleEG/test/SimpleEG_cfg.yml --sweep --note sweep # TODO re-enable
