image: citcat/dune-env:2.4

variables:
  DUNE_CONTROL_PATH: /opt/dune:$CI_PROJECT_DIR

stages:
- main

before_script:
  - cd /opt/dune

build_job:
  stage: main
  tags:
  - docker
  script:
  - ./dune-common/bin/dunecontrol --only=citcat all
  - cd /builds/citcat/citcat/build-cmake
  - make doc
  - make test