# Continuous Integration and Deployment of Utopia Framework Repository
---
# ++ Pipeline preparations ++++++++++++++++++++++++++++++++++++++++++++++++++++
variables:
  # For __deployment__, the Utopia version
  UTOPIA_VERSION: "1.0"
  # NOTE Currently unused, but should be used in docker image deployment.
  # TODO Single-source this

  # Variables needed for docker image deployment
  # The different segments of the resulting test image tag
  BASE_IMAGE_UBUNTU_VERSION: focal  # NOTE Adjust upon new Ubuntu Release
  BASE_IMAGE_VERSION: "1"           # NOTE Increment when changing dockerfile
  BASE_IMAGE_NAME: ccees/utopia-base
  BASE_IMAGE: "${BASE_IMAGE_NAME}:${BASE_IMAGE_UBUNTU_VERSION}-v${BASE_IMAGE_VERSION}"
  # NOTE Do not forget to increment the BASE_IMAGE_VERSION when changes to the
  #      docker file are introduced.

  # Variables controlling the deployed Utopia image and its development
  # counterpart (deployed from the ci_test stage for testing)
  UTOPIA_IMAGE_NAME: ccees/utopia
  UTOPIA_IMAGE_REMOTE_URL: https://ts-gitlab.iup.uni-heidelberg.de/utopia/utopia.git

  UTOPIA_DEV_IMAGE_TAG: dev
  UTOPIA_DEV_IMAGE_CHECKOUT: master

  # Setting number of processes for build jobs and DIND jobs
  CPUS_BUILD: 4
  CPUS_TEST: 4
  CPUS_DIND: 4

  # Build flags
  MAKE_FLAGS_BUILD: -j$CPUS_BUILD
  MAKE_FLAGS_TEST: -j$CPUS_TEST

  # Utopia virtual environment shortcuts
  RUN_IN_UTOPIA_ENV: $CI_PROJECT_DIR/build/run-in-utopia-env
  ENTER_UTOPIA_ENV: source $CI_PROJECT_DIR/build/activate

  # Docker Hub login command
  DOCKER_HUB_LOGIN: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
  # NOTE Both variables here are secret and protected variables. While the
  #      login command will complain, using --password-stdin actually EXPOSES
  #      the variable! No no.

  # Documentation server configuration
  DOC_HOST: root@hermes.iup.uni-heidelberg.de
  DOC_PORT: 2022      # ... forwards to utopia_doc_server container. root ok ;)
  DOC_REMOTE_BASE_DIR: /var/utopia_doc
  DOC_REMOTE_PATH: $DOC_REMOTE_BASE_DIR/$CI_COMMIT_REF_SLUG


stages:
  - setup     # (on master) set up the docker base image
  - build     # build utopia and all tests
  - test      # carry out tests
  - deploy    # (on master) deploy documentation; build and deploy docker image


# As base image for the jobs, use the Utopia image created in the setup stage
image: ${BASE_IMAGE}


# .. YAML Templates ...........................................................
# This makes includes below easier using the `<<: *anchor_name` syntax

# To install the python environment, the configuration needs access to
# external but private repositories; by adding a deploy key to selected jobs,
# the pull from these repositories becomes possible. The key is available under
# the SSH_PRIVATE_KEY variable.
.ssh-access: &ssh_access
  before_script:
    # For outside dependencies, use the "Utopia CI" deploy key
    # Instructions:
    #   https://docs.gitlab.com/ce/ci/ssh_keys/
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    # We're using tr to fix line endings which makes ed25519 keys work
    # without extra base64 encoding.
    # https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    # Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add the known hosts lists to ensure this ssh connection is the right one
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts


# Use the Docker-in-Docker executor and services, log into Docker Hub
.dind: &dind
  image: docker:stable
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - $DOCKER_HUB_LOGIN


# Create artifacts of the build directory
.artifacts: &artifacts
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build       # Build files
      - $CI_PROJECT_DIR/python      # Editably-installed python code
      - $CI_PROJECT_DIR/.config     # Frontend configuration files
    expire_in: 3 hours


# ++ Job definitions ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


# -- Setup stage --------------------------------------------------------------
# This stage takes care to build the utopia base testing image

setup:utopia-base:
  <<: *dind
  stage: setup
  only:
    - master
    - web
  script:
    - docker build -f docker/utopia-base.dockerfile
                   -t $BASE_IMAGE
                   --build-arg UBUNTU_VERSION=${BASE_IMAGE_UBUNTU_VERSION}
                   .
    - docker push $BASE_IMAGE


# -- Build stage --------------------------------------------------------------
# In this stage, the tests, models, and documentation is built
# The artifacts of the tests and models jobs are needed in the test stage

# Build the documentation; artifacts used for documentation deployment
build:docs:
  stage: build
  <<: *ssh_access
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build/doc
    expire_in: 1 day
  script:
    - mkdir build && cd build
    - cmake ..
    - make doc

# Build the unit tests; artifacts used in test stage
build:tests_core: &build_tests_core
  stage: build
  <<: [*ssh_access, *artifacts]
  script:
    - mkdir build && cd build
    - cmake -DCPP_COVERAGE=On ..
    - make $MAKE_FLAGS_BUILD build_tests_core

build:tests_dataio:
  <<: *build_tests_core
  script:
    - mkdir build && cd build
    - cmake -DCPP_COVERAGE=On ..
    - make $MAKE_FLAGS_BUILD build_tests_dataio

# Build the models and their tests; artifacts used in test stage
build:models:
  stage: build
  <<: [*ssh_access, *artifacts]
  script:
    - mkdir build && cd build
    - cmake -DCPP_COVERAGE=On ..
    - make $MAKE_FLAGS_BUILD all
    - make $MAKE_FLAGS_BUILD build_tests_models
  after_script:
    # Copy the frontend configuration to the project dir such that it is part
    # of the artifacts and can be re-used in the test stages
    - cp -r ~/.config $CI_PROJECT_DIR/

# Build in debug mode, once with gcc and once with clang
build:debug: &build_debug
  stage: build
  <<: *ssh_access
  allow_failure: true
  variables:
    CXXFLAGS: -Werror
  script:
    - mkdir build && cd build
    - cmake
        -DCMAKE_BUILD_TYPE=Debug
      ..
    # Build all the tests
    - make $MAKE_FLAGS_BUILD build_tests_core
    - make $MAKE_FLAGS_BUILD build_tests_dataio
    - make $MAKE_FLAGS_BUILD build_tests_models
    # Test that additional convenience targets exist
    - make $MAKE_FLAGS_BUILD build_tests_backend
    - make $MAKE_FLAGS_BUILD build_tests_all
    # Build all the models
    - make $MAKE_FLAGS_BUILD all

build:debug-clang:
  <<: *build_debug
  variables:
    CC: clang
    CXX: clang++
    CXXFLAGS: -Werror
  script:
    - mkdir build && cd build
    - cmake
        -DCMAKE_BUILD_TYPE=Debug
      ..
    # Build all the tests
    - make $MAKE_FLAGS_BUILD build_tests_core
    - make $MAKE_FLAGS_BUILD build_tests_dataio
    - make $MAKE_FLAGS_BUILD build_tests_models
    # Test that additional convenience targets exist
    - make $MAKE_FLAGS_BUILD build_tests_backend
    - make $MAKE_FLAGS_BUILD build_tests_all
    # Build all the models
    - make $MAKE_FLAGS_BUILD all

build:install:
  stage: build
  <<: *ssh_access
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build
      - $CI_PROJECT_DIR/install # installation directory
    expire_in: 3 hours
  script:
    - mkdir build && cd build
    - cmake
        -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
        -DCMAKE_BUILD_TYPE=Release
        ..
    - make $MAKE_FLAGS_BUILD install
    - cp -r ~/.cmake . # copy the packgage registry


# -- Test stage ---------------------------------------------------------------
# Using the artifacts of the build stage, executes tests of core, data I/O,
# frontend, models, and CLI.

test:core: &test_core
  stage: test
  <<: *ssh_access
  dependencies:
    - build:tests_core
  needs: ["build:tests_core"]
  variables:
    GCOVR_PATHS:
      --root $CI_PROJECT_DIR
      --filter $CI_PROJECT_DIR/include/utopia/core
  script:
    - cd build
    - make $MAKE_FLAGS_TEST test_core
  after_script: # NOTE: This will always execute, even if the script fails
    - source $CI_PROJECT_DIR/build/activate
    - pip3 install gcovr
    - cd $CI_PROJECT_DIR/build
    - mkdir coverage
    # Run once for report in HTML format
    - gcovr $GCOVR_PATHS --html --html-details -o coverage/report.html
    # Run again for coverage report in GitLab
    - gcovr $GCOVR_PATHS
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts: &coverage_artifacts
    name: "$CI_JOB_NAME"
    expose_as: Coverage report of Core tests
    paths:
      - build/coverage/
    expire_in: 1 week

test:dataio:
  <<: *test_core
  dependencies:
    - build:tests_dataio
  needs: ["build:tests_dataio"]
  variables:
    GCOVR_PATHS:
      --root $CI_PROJECT_DIR
      --filter $CI_PROJECT_DIR/include/utopia/data_io
  script:
    - cd build
    - make $MAKE_FLAGS_TEST test_dataio
  artifacts:
    <<: *coverage_artifacts
    expose_as: Coverage report of DataIO tests

test:utopya:
  stage: test
  dependencies:
    - build:models
  needs: ["build:models"]
  before_script:
    # Place a symlink at the expected path to make the model registry available
    - &add_cfg_symlink ln -s $CI_PROJECT_DIR/.config ~/.config && ls -la ~/
  script:
    - cd build
    - make test_utopya
  retry:
    max: 2
    when: script_failure

test:models:
  stage: test
  <<: *test_core
  dependencies:
    - build:models
  needs: ["build:models"]
  variables:
    # Exclude any paths containing 'test'
    GCOVR_PATHS:
      --root $CI_PROJECT_DIR
      --filter $CI_PROJECT_DIR/src/utopia/models
      --exclude '.*[Tt]est.*'
  before_script:
    # Make model registry available (from build:models job)
    - *add_cfg_symlink
  script:
    # Test models using C++ and Python model tests
    - cd build
    - make $MAKE_FLAGS_TEST test_models

    # Also test each model via the CLI.
    # Need to enter the virtual env first
    - $ENTER_UTOPIA_ENV

    # First, the test and benchmark models:
    - utopia run dummy --debug
    - utopia run CopyMeGraph --debug
    - utopia run CopyMeGrid --debug
    - utopia run CopyMeBare --debug --no-plot
    - utopia run HdfBench --sweep --num-seeds 3 --debug

    # Now the actual models:
    - utopia run ContDisease --debug
    - utopia run Environment --debug --num-steps 10
    - utopia run ForestFire --debug
    - utopia run GameOfLife --debug
    - utopia run Geomorphology --debug
    - utopia run PredatorPrey --debug
    - utopia run SandPile --debug
    - utopia run SEIRD --debug --num-steps 50
    - utopia run SimpleEG --debug
    - utopia run Vegetation --debug
  artifacts:
    <<: *coverage_artifacts
    expose_as: Coverage report of Model tests

test:cli:
  stage: test
  dependencies:
    - build:models
  needs: ["build:models"]
  artifacts:
    name: utopia_output
    paths:
      - $CI_PROJECT_DIR/utopia_output/
    expire_in: 1h
  before_script:
    # Make model registry available (from build:models job)
    - *add_cfg_symlink
  script:
    # Now, enter the virtual environment and test the CLI
    - $ENTER_UTOPIA_ENV

    # Test deployment of user configuration
    - utopia config user --deploy

    # Adjust the user configuration to store to a local directory
    - utopia config user --set paths.out_dir=$CI_PROJECT_DIR/utopia_output --get

    # Show which models are available
    - utopia models
    - utopia models ls --long

    # Test the run command
    - utopia run dummy

    # Test passing a custom run configuration and performing a sweep
    - utopia run dummy python/model_tests/dummy/sweep.yml --sweep --note sweep

    # Test setting the number of steps (negative should fail)
    - utopia run dummy --num-steps 1 --no-plot
    - if utopia run dummy --num-steps -1; then exit 1; else echo "all good"; fi

    # Test setting the number of seeds (<= 1 should fail)
    - utopia run dummy --num-seeds 2 --sweep --no-plot --note sweep_via_cli
    - if utopia run dummy --num-seeds 1; then exit 1; else echo "all good"; fi

    # Test debug mode and setting simulation errors level
    - utopia run dummy --note debug0 --num-steps 3 --debug
    - utopia run dummy --note debug1 --num-steps 3 --debug --sim-errors warn

    # Write start and step
    - utopia run dummy --note write_sparse --num-steps 5 --write-every 2
    - utopia run dummy --note write_last --num-steps 5 --write-start 5

    # Test the printing of the data tree
    # NOTE Need to sleep here because the eval directory will already exist
    - utopia run dummy --full-data-tree
    - sleep 1.1 && utopia eval dummy --full-data-tree
    - utopia run dummy --suppress-data-tree
    - sleep 1.1 && utopia eval dummy --suppress-data-tree

    # Test the plotting capabilities
    - utopia run dummy --note plt0 --no-plot
    - sleep 1.1 && utopia eval dummy  # should create the corresponding plots

    - utopia run dummy --note plt1
    - utopia run dummy --note plt2 --plot-only states
    - utopia run dummy --note plt3
        --plots-cfg src/utopia/models/dummy/dummy_plots.yml
    - utopia run dummy --note plt4
        --update-plots-cfg state_step_1.based_on=states state_step_1.step=1
    - utopia run dummy --note plt5
        --update-plots-cfg src/utopia/models/dummy/dummy_plots.yml

    # Test the interactive plotting mode, piping mock input to it
    # None of these should lead to an exit code other than 0
    - sleep 1.1 && utopia eval --interactive dummy
        <<< $'\n--plot-only states\n--plot-only state_mean --debug'
    - sleep 1.1 && utopia eval --interactive dummy
        <<< $'--debug\n--debug --update-plots-cfg state_mean.foo=bar'
    - sleep 1.1 && utopia eval --interactive dummy
        <<< $'--plot-only some_non_existing_plot --debug'
    - sleep 1.1 && utopia eval --interactive dummy
        <<< $'--plot-only some_non_existing_plot --debug'
    - sleep 1.1 && utopia eval --interactive dummy
        <<< $'some offending arguments\n--help'

    # Test the setting of parameters and config parameters from CLI
    - utopia run dummy --set-model-params foo=3 bar=2.0
    - utopia run dummy --set-params num_steps=3 write_every=2
    - utopia run dummy --set-cfg parameter_space.seed=23

    # Test the model copying, first as a dry run, then for real
    - utopia models copy dummy --new-name FooBar --target-project Utopia --non-interactive --dry-run
    - utopia models copy dummy --new-name FooBar --target-project Utopia --non-interactive

    # Test that it is registered. Note: Does not test building!
    - cd build && cmake ..
    - if utopia models ls | grep -q FooBar; then echo "Found copied FooBar!"; else echo "Could not find copied FooBar model!" && exit 1; fi

    # Attempting to copy it again should fail
    - if utopia models copy dummy --new-name FooBar --target-project Utopia --non-interactive --dry-run; then exit 1; else echo "\nFailed as expected!"; fi

    # Test model registry entry removal interface; do this last, obviously
    - utopia models rm dummy HdfBench
    - if utopia run dummy; then exit 1; else echo "\nFailed as expected"; fi
    - utopia models rm --all
    - if utopia run SandPile; then exit 1; else echo "\nFailed as expected"; fi


# Test if using Utopia in a downstream module works
test:link_build_tree: &test_link
  stage: test
  dependencies:
    - build:install
  needs: ["build:install"]
  script:
    # move the package registry into the user path
    - cd build && cp -r .cmake ~/
    # build downstream module
    - cd $CI_PROJECT_DIR && mkdir build-dep && cd build-dep
    # package should be found via registry
    - cmake ../test/dependency
    - make $MAKE_FLAGS_BUILD all
    - make test

test:link_install_tree:
  <<: *test_link
  script:
    # build downstream module
    - mkdir build-dep && cd build-dep
    # CMake v3.10 is restricted to _DIR, CMake >=v3.14 can use _ROOT
    - cmake
        -DUtopia_DIR=$CI_PROJECT_DIR/install/lib/cmake/Utopia
        -DUtopia_ROOT=$CI_PROJECT_DIR/install
        ../test/dependency
    - make $MAKE_FLAGS_BUILD all
    - make test


# -- Deploy Stage -------------------------------------------------------------
# Deploy the documentation to a self-hosted web server
deploy:docs:
  stage: deploy
  <<: *ssh_access
  only:
    - branches@utopia/utopia
  dependencies:
    - build:docs
  needs: ["build:docs"] # May execute out of order if dependencies are ready
  script:
    # Create the directory on the remote, removing any prior version
    - echo "Creating remote directory $DOC_REMOTE_PATH ..."
    - ssh -p $DOC_PORT $DOC_HOST "rm -rf $DOC_REMOTE_PATH"
    - ssh -p $DOC_PORT $DOC_HOST "mkdir -p $DOC_REMOTE_PATH/doxygen/"

    # Copy sphinx & doxygen HTML documentation to remote
    - cd build/doc
    - echo "Uploading documentation to $DOC_REMOTE_PATH/ ..."
    - scp -P $DOC_PORT -pr html         $DOC_HOST:$DOC_REMOTE_PATH/
    - scp -P $DOC_PORT -pr doxygen/html $DOC_HOST:$DOC_REMOTE_PATH/doxygen/

    - echo "Finished. :)"

  environment:
    name: docs/$CI_COMMIT_REF_NAME
    url: https://hermes.iup.uni-heidelberg.de/utopia_doc/$CI_COMMIT_REF_SLUG/html/
    on_stop: deploy:stop_docs

# Stop the deployed "docs" environment for this branch
# NOTE: This job is automatically executed if the original branch is deleted
#       (*GitLab Magic*) or someone stops the environment.
deploy:stop_docs:
  stage: deploy
  when: manual # Also triggered on branch deletion
  variables:
    # Stop GitLab from checking out the commit again (branch is deleted!)
    GIT_STRATEGY: none
  dependencies: []
  # NOTE: Same "needs" as for "deploy:docs", because on_stop relation does not
  #       work otherwise (this might be a bug?)
  needs: ["build:docs"]

  <<: *ssh_access
  script:
    - echo "Removing remote directory $DOC_REMOTE_PATH ..."
    - ssh -p $DOC_PORT $DOC_HOST "rm -rf $DOC_REMOTE_PATH"

    - echo "It's gone. :)"

  environment:
    name: docs/$CI_COMMIT_REF_NAME
    action: stop


# Build and deploy the docker image to docker hub: ccees/utopia:latest
deploy:dockerhub-latest:
  <<: *dind
  stage: deploy
  only:
    - master
  script:
    # Now, build the docker image and push it as $UTOPIA_IMAGE_NAME:latest
    - docker build -f docker/utopia.dockerfile
                   --build-arg BASE_IMAGE=$BASE_IMAGE
                   --build-arg PROCNUM=$CPUS_DIND
                   --build-arg GIT_CHECKOUT=master
                   --build-arg GIT_REMOTE_URL=$UTOPIA_IMAGE_REMOTE_URL
                   -t $UTOPIA_IMAGE_NAME:latest
                   ./
    - docker push $UTOPIA_IMAGE_NAME:latest
  environment:
    name: docker/latest
    url: https://hub.docker.com/r/$UTOPIA_IMAGE_NAME
