image: citcat/dune-env:2.4

variables:
  DUNE_CONTROL_PATH: /opt/dune:$CI_PROJECT_DIR
  COMPILER_FLAGS: -O3

stages:
- build

before_script:
  - cd /opt/dune

build_job:
  stage: build
  tags:
  - docker
  script:
  - export CMAKE_FLAGS="-DCMAKE_CXX_FLAGS='$COMPILER_FLAGS'"
  - ./dune-common/bin/dunecontrol --only=citcat all
  - ./dune-common/bin/dunecontrol --only=citcat bexec make doc