image: citcat/dune-env:latest
variables:
  PROCNUM: 2
  DUNE_CONTROL_PATH: /opt/dune:$CI_PROJECT_DIR
  RUN_IN_DUNE_ENV: $CI_PROJECT_DIR/build-cmake/run-in-dune-env
  CONFIG_FLAGS:
      -DDUNE_PYTHON_VIRTUALENV_SETUP=True
      -DDUNE_PYTHON_ALLOW_GET_PIP=True
  MAKE_FLAGS_BUILD:
      -j $PROCNUM
before_script:
  - cd /opt/dune

stages:
  - build
  - test

build:main:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build-cmake
    expire_in: 3 hours
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol update
    - CMAKE_FLAGS="$CONFIG_FLAGS"
      ./dune-common/bin/dunecontrol --module=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make doc
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD build_tests
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD all
    # TODO move building of models into separate stage

build:debug:
  stage: build
  allow_failure: true
  tags:
    - light
  script:
    - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CONFIG_FLAGS -DCMAKE_CXX_FLAGS_DEBUG='$CMAKE_CXX_FLAGS_DEBUG -Werror'"
      ./dune-common/bin/dunecontrol --only=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD build_tests

build:models:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build-cmake
    expire_in: 3 hours
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol update
    - CMAKE_FLAGS="$CONFIG_FLAGS"
      ./dune-common/bin/dunecontrol --module=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make $MAKE_FLAGS_BUILD all

test:core:
  stage: test
  dependencies:
    - build:main
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol --only=utopia make test_core

test:dataio:
  stage: test
  dependencies:
    - build:main
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol --only=utopia make test_dataio

test:python:
  stage: test
  dependencies:
    - build:main
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol --only=utopia configure
    - ./dune-common/bin/dunecontrol --only=utopia make test_python

test:models:
  stage: test
  dependencies:
    - build:models
  tags:
    - light
  script:
    - ./dune-common/bin/dunecontrol --only=utopia configure
    - $RUN_IN_DUNE_ENV utopia dummy 
      $CI_PROJECT_DIR/dune/utopia/models/dummy/dummy_cfg.yml --sweep
