# pre-commit configuration for Utopia
#
# NOTE See pyproject.toml for configuration options for some of these tools
---
repos:
  # Manually run this every now and again .....................................
  # Command:  pre-commit run --all-files --hook-stage manual

  # Run if desiring to make use of newer language features
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      name: upgrade python syntax
      args:
        - --py3-plus
        - --py37-plus
      stages: [manual]

  # Default pre-commit hooks ..................................................
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: sort imports
        additional_dependencies: [toml]
        types: [python]
        args: [--project=utopya]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black code formatting
        types: [python]
        args: [--safe]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
        name: check RST backticks

  # TODO Consider activating these as well -- but they cause many changes
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.1.0
  #   hooks:
  #     - id: end-of-file-fixer
  #       name: fix end of files

  #     - id: trailing-whitespace
  #       name: fix trailing whitespace
  #       args: [--markdown-linebreak-ext=md]
