# The default plots of the CopyMe model. Can use the `based_on` feature...
---
# Spatial CA animations .......................................................
ca/parameter:
  based_on: ca/parameter

trajectory:
  based_on: trajectory
